# Generated by Django 3.2.3 on 2022-05-01 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=100)),
                ('pin', models.IntegerField()),
                ('job', models.CharField(choices=[('carpenter', 'CARPENTER'), ('plumber', 'PLUMBER'), ('electrician', 'ELECTRICIAN'), ('mechanic', 'MECHANIC'), ('painter', 'PAINTER')], default='carpenter', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
