# Generated by Django 4.2.4 on 2023-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0005_alter_customerappointments_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_customer",
            field=models.BooleanField(default=True, verbose_name="customer status"),
        ),
    ]
