# Generated by Django 3.2.3 on 2022-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=100)),
                ('job_phnnumber', models.IntegerField()),
                ('job_image', models.CharField(default='https://p.kindpng.com/picc/s/79-798754_hoteles-y-centros-vacacionales-dish-placeholder-hd-png.png', max_length=500)),
            ],
        ),
    ]
